language: go

before_script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- npm install --verbose

script:
- go test -v -coverprofile=ndt.cov github.com/m-lab/ndt-cloud
- $GOPATH/bin/goveralls -coverprofile=ndt.cov -service=travis-ci
