language: go
go:
- "1.11"

services:
- docker

before_script:
- go get github.com/mattn/goveralls
- npm install --verbose ws minimist

script:
- docker build -f TestDockerfile -t ndt-server-test --build-arg DIRECTORY=`pwd` .
- docker run -t
    -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID
    -e TRAVIS=true
    -e COVERALLS_SERVICE_NAME=travis-ci
    ndt-server-test
- docker build . -f Dockerfile -t m-lab/ndt-server

# Need a deployment section which calls "docker push"
