# We don't care about the language because we build in a docker. Not doing
# that and instead requiring go leads to failures caused by missing headers
# on the build machine. So we use minimal, which is basically "no lang".
#
# See <https://docs.travis-ci.com/user/languages/minimal-and-generic/>
# See <https://travis-ci.org/m-lab/ndt-server/builds/496487913>
language: minimal
dist: xenial

services:
- docker

script:
- docker build -f TestDockerfile -t ndt-server-test .
- docker run -t
    -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID
    -e TRAVIS=true
    -e COVERALLS_SERVICE_NAME=travis-ci
    ndt-server-test
- docker build . -f Dockerfile -t m-lab/ndt-server

# Need a deployment section which calls "docker push"
