language: go
go:
- "1.11"

services:
- docker

before_script:
- go get github.com/mattn/goveralls
- npm install --verbose ws minimist

script:
- docker build -f TestDockerfile -t m-lab/ndt-server-test --build-arg DIRECTORY=`pwd` .
- docker run -it -v `pwd`:`pwd` -w `pwd` m-lab/ndt-server-test
- $GOPATH/bin/goveralls -coverprofile=ndt.cov -service=travis-ci
- docker build . -f Dockerfile -t m-lab/ndt-server

# Need a deployment section which calls "docker push"
