version: '3.7'
services:
  ndt-server:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./certs:/certs
      - ./datadir:/datadir
      - ./html:/html
    cap_drop:
      - ALL
    ports:
      - "443:4443"
    command: [
      "./ndt-server",
      "-cert", "/certs/cert.pem",
      "-key", "/certs/key.pem",
      "-datadir", "/datadir",
      "-ndt7_addr", ":4443"
    ]
