-
  name: Install Git, yum-utils and Docker
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Add repository
      yum_repository:
        name: docker
        description: Docker Repo
        file: docker-ce
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: yes
        gpgcheck: no
    - name : Install iperf
      yum:
        name: https://ftp.tu-chemnitz.de/pub/linux/dag/redhat/el7/en/x86_64/rpmforge/RPMS/iperf-2.0.4-1.el7.rf.x86_64.rpm
        state: present

    - name:  Install
      yum:
        state: present
        name:
          - git
          - yum-utils
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Disable Firewall
      systemd:
        name: firewalld
        enabled: no
        state: stopped
    - git:
         repo: 'https://github.com/satomiie/performance-ndt-server.git'
         dest: "{{ path }}/performance-ndt-server/"
         clone: yes
         force: yes
    - name: Prepare the runtime environment
      shell: /usr/sbin/install -d certs datadir
      args:
        chdir: "{{ path }}"
    - name: Generate Self-signed certificates
      shell: gen_local_test_certs.bash
      args:
        chdir: "{{ path }}"
    - name: build the docker container
      docker_image:
        name: ndt_server
        path: "{{ path }}"
    - name: Copy service to startup
      copy:
        src: "{{ path }}/intx-perfserver.service"
        dest: /etc/systemd/system/
        owner: root
        group: root
