-
  name: Install and configure iperf with ndt-server
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Add Docker repository
      yum_repository:
        name: docker
        description: Docker Repo
        file: docker-ce
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: yes
        gpgcheck: no
    - name : Install iperf
      yum:
        name: https://ftp.tu-chemnitz.de/pub/linux/dag/redhat/el7/en/x86_64/rpmforge/RPMS/iperf-2.0.4-1.el7.rf.x86_64.rpm
        state: present
    - name:  Install Packages for ndt-server
      yum:
        state: present
        name:
          - git
          - yum-utils
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Disable Firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: no
    - name: Disable SELinux
      replace:
        path: /etc/selinux/config
        regexp: 'SELINUX=enforcing'
        replace: 'SELINUX=disabled'
    - name: Enable docker
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: Add Netforwarding enable
      lineinfile:
           path: /etc/sysctl.conf
           line: net.ipv4.ip_forward=1
    - name: Add git repository for services
      git:
         repo: 'https://github.com/satomiie/performance-ndt-server.git'
         dest: "{{ path_service }}"
         clone: yes
         force: yes

    - name: Add git repository for ndt-server
      git:
         repo: 'https://github.com/m-lab/ndt-server.git'
         dest: "{{ path_ndt }}"
         clone: yes
         force: yes
         update: yes
    - name: Create datadir folder for certificates
      file:
          path: "{{ path_ndt }}/datadir"
          state: directory
          owner: root
          group: root
          mode: 0775
    - name: Create Certs folder
      file:
          path: "{{ path_ndt }}/certs"
          state: directory
          owner: root
          group: root
          mode: 0775
    - name: Change certificate validity to 10 years
      replace:
          path: "{{ path_ndt }}/gen_local_test_certs.bash"
          regexp: '-days 2'
          replace: '-days 36500'
    - name : Check certificates
      stat:
        path: '{{ path_ndt}}/certs/cert.pem'
      register: cert_file

    - name: Generate Self-signed certificates
      command: ./gen_local_test_certs.bash
      args:
          chdir: "{{ path_ndt }}"
      when: not cert_file.stat.exists


    - name: build the docker container
      command: docker build . -t ndt-server
      args:
          chdir: "{{ path_ndt }}"
    - name: Copy service to startup
      copy:
        src: "{{ path_service }}/Service/perfserver.service"
        dest: /etc/systemd/system/
        remote_src: yes
        owner: root
        group: root
    - name: Copy script
      copy:
        src: "{{ path_service }}/Service/ndt-server-service.sh"
        dest: "{{ path_ndt }}"
        remote_src: yes
        owner: root
        group: root
        mode: 0755
    - name: Reload Daemon
      systemd:
        daemon_reload: yes
    - name: Enable Service
      systemd:
        name: perfserver
        enabled: yes
        state: started
    - name: Clean artifact path
      file:
        state: absent
        path: "{{ path_service }}"
